# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "pybox"
  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "pybox-test" do |pybox|
    pybox.vm.hostname = "pybox-test"
  end
end
